### ISSUE TITLE
Standard example fails with "Data Bag Items must contain a Hash or Mash!"

### ISSUE THREAD

**Issue by Yserz** [chef-cookbooks/chef-vault#20]
Using the standard example from the cookbook readme fails with:

`Data Bag Items must contain a Hash or Mash!`

code:
```
chef_gem 'chef-vault'
include_recipe 'chef-vault'
...snip...
begin
  data_bag('credentials')
rescue
  ruby_block "create-data_bag-secrets" do
    block do
      Chef::DataBag.validate_name!('credentials')
      databag = Chef::DataBag.new
      databag.name('credentials')
      databag.save
    end
    action :create
  end
end

chef_vault_secret 'chef_server_password' do
  data_bag 'credentials'
  raw_data({'auth' => 'Forged in a mold'})
  admins ['admin']
  clients 'vm-chef-workstation'
  search '*:*'
  action :create
end
```
chef-client 12.0.0

Full stacktrace:
```
==> vm-chef-server: ================================================================================
==> vm-chef-server: Recipe Compile Error in /etc/chef-server/chef-solo-1/cookbooks/wlc-chef-server/recipes/upload.rb
==> vm-chef-server: ================================================================================
==> vm-chef-server: 
==> vm-chef-server: 
==> vm-chef-server: Chef::Exceptions::ValidationFailed
==> vm-chef-server: 
==> vm-chef-server: ----------------------------------
==> vm-chef-server: Data Bag Items must contain a Hash or Mash!
==> vm-chef-server: 
==> vm-chef-server: Cookbook Trace:
==> vm-chef-server: ---------------
==> vm-chef-server:   /opt/chef/embedded/apps/chef/lib/chef/data_bag_item.rb:75:in `raw_data='
==> vm-chef-server:   /opt/chef/embedded/apps/chef/lib/chef/data_bag_item.rb:126:in `from_hash'
==> vm-chef-server:   /opt/chef/embedded/apps/chef/lib/chef/data_bag_item.rb:155:in `load'
==> vm-chef-server:   /etc/chef-server/chef-solo-1/cookbooks/chef-vault/libraries/chef_vault_item.rb:43:in `rescue in chef_vault_item'
==> vm-chef-server:   /etc/chef-server/chef-solo-1/cookbooks/chef-vault/libraries/chef_vault_item.rb:40:in `chef_vault_item'
==> vm-chef-server:   /etc/chef-server/chef-solo-1/cookbooks/wlc-chef-server/recipes/default.rb:53:in `from_file'
==> vm-chef-server: 
==> vm-chef-server:   /opt/chef/embedded/apps/chef/lib/chef/mixin/from_file.rb:30:in `instance_eval'
==> vm-chef-server:   /opt/chef/embedded/apps/chef/lib/chef/mixin/from_file.rb:30:in `from_file'
==> vm-chef-server: 
==> vm-chef-server:   /opt/chef/embedded/apps/chef/lib/chef/cookbook_version.rb:245:in `load_recipe'
==> vm-chef-server:   /opt/chef/embedded/apps/chef/lib/chef/run_context.rb:169:in `load_recipe'
==> vm-chef-server:   /opt/chef/embedded/apps/chef/lib/chef/run_context.rb:138:in `block in include_recipe'
==> vm-chef-server:   /opt/chef/embedded/apps/chef/lib/chef/run_context.rb:137:in `each'
==> vm-chef-server:   /opt/chef/embedded/apps/chef/lib/chef/run_context.rb:137:in `include_recipe'
==> vm-chef-server:   /opt/chef/embedded/apps/chef/lib/chef/dsl/include_recipe.rb:26:in `include_recipe'
==> vm-chef-server:   /etc/chef-server/chef-solo-1/cookbooks/wlc-chef-server/recipes/upload.rb:9:in `from_file'
==> vm-chef-server:   /opt/chef/embedded/apps/chef/lib/chef/mixin/from_file.rb:30:in `instance_eval'
==> vm-chef-server:   /opt/chef/embedded/apps/chef/lib/chef/mixin/from_file.rb:30:in `from_file'
==> vm-chef-server:   /opt/chef/embedded/apps/chef/lib/chef/cookbook_version.rb:245:in `load_recipe'
==> vm-chef-server:   /opt/chef/embedded/apps/chef/lib/chef/run_context.rb:169:in `load_recipe'
==> vm-chef-server:   /opt/chef/embedded/apps/chef/lib/chef/run_context/cookbook_compiler.rb:140:in `block in compile_recipes'
==> vm-chef-server:   /opt/chef/embedded/apps/chef/lib/chef/run_context/cookbook_compiler.rb:138:in `each'
==> vm-chef-server:   /opt/chef/embedded/apps/chef/lib/chef/run_context/cookbook_compiler.rb:138:in `compile_recipes'
==> vm-chef-server:   /opt/chef/embedded/apps/chef/lib/chef/run_context/cookbook_compiler.rb:75:in `compile'
==> vm-chef-server:   /opt/chef/embedded/apps/chef/lib/chef/run_context.rb:92:in `load'
==> vm-chef-server:   /opt/chef/embedded/apps/chef/lib/chef/policy_builder/expand_node_object.rb:73:in `setup_run_context'
==> vm-chef-server:   /opt/chef/embedded/apps/chef/lib/chef/client.rb:235:in `setup_run_context'
==> vm-chef-server:   /opt/chef/embedded/apps/chef/lib/chef/client.rb:397:in `run'
==> vm-chef-server: 
==> vm-chef-server:   /opt/chef/embedded/apps/chef/lib/chef/application.rb:261:in `block in fork_chef_client'
==> vm-chef-server:   /opt/chef/embedded/apps/chef/lib/chef/application.rb:249:in `fork'
==> vm-chef-server:   /opt/chef/embedded/apps/chef/lib/chef/application.rb:249:in `fork_chef_client'
==> vm-chef-server:   /opt/chef/embedded/apps/chef/lib/chef/application.rb:215:in `block in run_chef_client'
==> vm-chef-server:   /opt/chef/embedded/apps/chef/lib/chef/local_mode.rb:38:in `with_server_connectivity'
==> vm-chef-server:   /opt/chef/embedded/apps/chef/lib/chef/application.rb:201:in `run_chef_client'
==> vm-chef-server:   /opt/chef/embedded/apps/chef/lib/chef/application/solo.rb:245:in `block in interval_run_chef_client'
==> vm-chef-server:   /opt/chef/embedded/apps/chef/lib/chef/application/solo.rb:234:in `loop'
==> vm-chef-server:   /opt/chef/embedded/apps/chef/lib/chef/application/solo.rb:234:in `interval_run_chef_client'
==> vm-chef-server:   /opt/chef/embedded/apps/chef/lib/chef/application/solo.rb:224:in `run_application'
==> vm-chef-server:   /opt/chef/embedded/apps/chef/lib/chef/application.rb:58:in `run'
==> vm-chef-server:   /opt/chef/embedded/apps/chef/bin/chef-solo:25:in `<top (required)>'
==> vm-chef-server:   /usr/bin/chef-solo:40:in `load'
==> vm-chef-server:   /usr/bin/chef-solo:40:in `<main>'
==> vm-chef-server: 
==> vm-chef-server: Relevant File Content:
==> vm-chef-server: ----------------------
==> vm-chef-server: /opt/chef/embedded/apps/chef/lib/chef/data_bag_item.rb:
==> vm-chef-server: 
==> vm-chef-server:  68:  
==> vm-chef-server:  69:      def validate_id!(id_str)
==> vm-chef-server:  70:        self.class.validate_id!(id_str)
==> vm-chef-server: 
==> vm-chef-server:  71:      end
==> vm-chef-server: 
==> vm-chef-server:  72:  
==> vm-chef-server:  73:      def raw_data=(new_data)
==> vm-chef-server: 
==> vm-chef-server:  74:        unless new_data.respond_to?(:[]) && new_data.respond_to?(:keys)
==> vm-chef-server:  75>>         raise Exceptions::ValidationFailed, "Data Bag Items must contain a Hash or Mash!"
==> vm-chef-server:  76:        end
==> vm-chef-server:  77:        validate_id!(new_data["id"])
==> vm-chef-server:  78:        @raw_data = new_data
==> vm-chef-server:  79:      end
==> vm-chef-server:  80:  
==> vm-chef-server:  81:      def data_bag(arg=nil)
==> vm-chef-server:  82:        set_or_return(
==> vm-chef-server:  83:          :data_bag,
==> vm-chef-server:  84:          arg,
==> vm-chef-server: 
==> vm-chef-server: 
==> vm-chef-server: 
==> vm-chef-server: [2014-12-25T18:53:57+00:00] ERROR: Running exception handlers
==> vm-chef-server: [2014-12-25T18:53:57+00:00] ERROR: Exception handlers complete
==> vm-chef-server: [2014-12-25T18:53:57+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
==> vm-chef-server: [2014-12-25T18:53:57+00:00] ERROR: Data Bag Items must contain a Hash or Mash!
==> vm-chef-server: [2014-12-25T18:53:58+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

**Comment by jtimberman** [comment]
You're hitting the fallback to a Chef::DataBagItem, this isn't using Chef Vault.

**Comment by joelwilson** [comment]
I got stuck on this all day yesterday. The problem had something to do with Chef 12 as it went away when I went back to using chef omnibus version 11.16.4. This is on a Windows 2012 vagrant machine. A Ubuntu 14.04 vagrant machine did not have any problems on Chef 12.

For anyone interested, you should be able to re-create with the following recipe and vagrantfile assuming you have set up your data bags properly (encrypted with your chef key).

Vagrant 1.6.5
VirtualBox 4.3.12

Vagrantfile

	VAGRANTFILE_API_VERSION = '2'
	Vagrant.require_version '>= 1.5.0'

	# Following Riot's convention. This is the data bag's name.
	ENVIRONMENT = 'myapp-dev'
	
	DATA_BAGS_PATH = 'data/bags/here'
	ENVIRONMENTS_PATH = 'files/environments'
	CHEF_HOME = 'your/chef/home'
	USER = ENV['USERNAME']

	Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
	  if Vagrant.has_plugin?("vagrant-omnibus")
		# Change to 11.16.4, then vagrant destroy and vagrant up to see it work!
		config.omnibus.chef_version = '12.0.3' 
	  end

	  config.vm.box = 'your-windows2012-box'
	  config.vm.network :private_network, ip: '10.2.2.2'
	  config.berkshelf.enabled = true
	  config.vm.hostname = 'chef-vault-test-berkshelf'

	  # Copy our client key to the VM so that the Chef run can decrypt the local
	  #   chef-vault data bag encrypted items.
	  config.vm.provision :file, source: "#{CHEF_HOME}/client.pem", destination: '/chef/client.pem'

	  config.vm.provision :chef_solo do |chef|
		chef.node_name = USER
		chef.environment = ENVIRONMENT
		chef.environments_path = ENVIRONMENTS_PATH
		chef.data_bags_path = DATA_BAGS_PATH

		chef.run_list = [
		  'recipe[chef-vault-test::default]'
		]
	  end
	end

Cookbook

	#
	# Cookbook Name:: chef-vault-test
	# Recipe:: default
	#

	include_recipe 'chef-vault'
	chef_vault_item('myapp-dev', 'credentials')

Un-encrypted data bag (in directory data_bags/myapp-dev)

	{
	  "id": "credentials",
	  "devusername": "devuser",
	  "devpassword": "password01",
	  "adminusername": "admin",
	  "adminpassword": "password02"
	}

A fix would be awesome because I would love to use chef 12.

**Comment by CaseyBurnsSv** [comment]
I had this error on Windows with ChefDK 12.

I fixed it. It was caused by a difference in capitalisation between the databag file and the id I was using in my recipe.

I suspect in my instance of this issue... it was caused by chef misreporting the issue. It should say "cannot find databag with id 'blah'" or similar?

**Comment by stefancarlton** [comment]
I had the same error reported - like @CaseyBurnsSv mine was a mismatch between the id attribute and the filename.

**Comment by Infectsoldier** [comment]
I had the same error. When i use chef-solo 11.8 its work fine, when 12 its didnt work

**Comment by eric-tucker** [comment]
What's going on with this issue?  Data bags that work under chef client running in zero mode do not work running under chef solo.  This seems like a very odd bug.

**Comment by DevOpsNinjaTurtle** [comment]
I have also been bitten by this recently. Would appreciate an update or workaround aside from downgrading.

**Comment by madhead** [comment]
I had exactly the same problem. I used Symbols to refer items in databags. The problem turned to be `chef-solo`. When you use `chef-solo` `Chef::DataBagItem` and `Chef::DataBag` [use some](https://github.com/chef/chef/blob/master/lib/chef/data_bag_item.rb#L148) [JSON parsing magic](https://github.com/chef/chef/blob/master/lib/chef/data_bag.rb#L114) to create databags (`Chef::DataBagItem` delegates to `Chef::DataBag`, second link). And JSON parsing results in `Hash`. `Hash` does not support Symbols as keys:

    irb(main):001:0> {"a"=>"b"}["a"]
    => "b"
    irb(main):002:0> {"a"=>"b"}[:a]
    => nil

you need [`Mash`](http://www.rubydoc.info/gems/chef/Mash).

When I switched to chef-zero, those `if`s go to another computation branches and use "server", which appears to return `Mash`es, this small change in `Vagrantfile`:

    -  config.vm.provision :chef_solo do |chef|
    +  config.vm.provision :chef_zero do |chef|

resolves this issues.

**Comment by jtimberman** [comment]
It seems that this issue isn't with the cookbook itself then.

**Comment by giladsh1** [comment]
duplidcated on mac os.
this issue is most likely caused by the chef 12 provisioner.
the workaround is to set `config.omnibus.chef_version = '11.18.12'` in Vagrantfile
This fixed the problem for me.
same issue can be found here - https://github.com/chef/chef/issues/3347
