### ISSUE TITLE
Fallback to encrypted databag

### ISSUE THREAD

**Issue by mferno** [chef-cookbooks/chef-vault#40]
Hello,

Is there a reason for `chef-vault` not supporting encrypted databag fallback? 

"Why not just use chef-vault which is actually loading your encrypted databags?", one might ask.   

The reason for **us** not being able to use the regular `chef-vault` functionality is because of the well known "chicken and egg" problem. I know there are ways around this which may be something we need to do but still, it would be nice to be able to fall back to encrypted databags as well.

I haven't made a solution proposal on this yet but if it sounds like a good idea I can do that.

Thanks,
Mathias

**Comment by jcarapet** [comment]
+1, but working on a solution. The issue I see being biggest is that multiple encryption keys might be used. Tougher to account for. My environment is a little bit different. I just copied method into own cookbook and added own logic handling encrypted data bags. 

```
  def chef_vault_item(bag, id)
    if ChefVault::Item.vault?(bag, id)
      ChefVault::Item.load(bag, id)
    elsif node['chef-vaultl']['databag_fallback']
      case ChefVault::Item.data_bag_item_type(bag, id)
      when :encrypted
        deploy_secret_file(SECRET_FILE, 'blahblah')
        decrypt(bag, id)
      when :normal
        Chef::DataBagItem.load(bag, id)
      end
    else
      Chef::Log.error('there is no data bag by that name on the chef-server')
    end
  end
```

**Comment by lamont-granquist** [comment]
this seems to have been implemented via `node['chef-vault']['databag_fallback']` some time ago.
