### ISSUE TITLE
Compile error on Chef 11

### ISSUE THREAD

**Issue by pwyliu** [chef-cookbooks/chef-vault#41]
Hello, 

I'm having trouble running `chef-vault 1.3.2` on nodes running Chef 11. When trying to converge, the following error appears:

```
SyntaxError
-----------
/var/chef/cache/cookbooks/chef-vault/libraries/matchers.rb:2: unknown type of %string
  %i(create update delete create_if_missing).each do |action|
```

I suspect this is because doing `i%(foo bar)` is a Ruby 2.x feature and Chef 11 embeds Ruby 1.9.

**Comment by haidangwa** [comment]
I concur. I have a wrapper cookbook that has chef-vault as an upstream dependency. When I run this in Test Kitchen with chef 11.18.6, I get this compile error, and chef 12.4.2 doesn't. Pinning my cookbok dependency to chef-vault '= 1.3.0' temporarily solves this issue for me.

**Comment by elnica6** [comment]
+1. I'm having the same issue.

**Comment by sniperd** [comment]
+1. Same issue as well.

**Comment by dpetzel** [comment]
I've also run into this issue. I don't even use chef-vault, but one of the community cookbooks I'm using has it listed as a dependency (for an optional code path).

**Comment by csghuser** [comment]
+1 Same here

**Comment by yurinnick** [comment]
+1

**Comment by csghuser** [comment]
As per @dpetzel , I'm not a user of chef-vault, but this is breaking the consul cookbook when trying to upload this to chef server using berks, as it is bringing down the latest version of chef-vault.

**Comment by devsathish** [comment]
+1 Im facing the same issue.

**Comment by luckymike** [comment]
:+1: just hit this trying to release a new sensu-chef

**Comment by luckymike** [comment]
This happens because the %i() syntax in `libraries/matchers.rb` is a Ruby 2.x-ism, so Chef 11's omnibus does not support it. There's a PR #42 which would resolve this, but that committer has not signed the CLA. @tas50 would you be able to add that change directly to fix this regression?
