### ISSUE TITLE
chef_vault_secrets should raise LoadError

### ISSUE THREAD

**Issue by poliva83** [chef-cookbooks/chef-vault#44]
chef_vault_secrets should raise LoadError when trying to load chef-vault gem instead of suppressing it.
https://github.com/chef-cookbooks/chef-vault/blob/master/libraries/chef_vault_secret.rb#L22

This LWRP does not run properly without chef-vault gem installed but will give cryptic exception during chef-client run rather then clear error message if error got raised.

**Comment by cheeseplus** [comment]
The cookbook has been reworked to install the gem via metadata.rb which provides much clearer errors.
