### ISSUE TITLE
Deletion of items using chef_vault_secret does not work.

### ISSUE THREAD

**Issue by poliva83** [chef-cookbooks/chef-vault#45]
```
chef_vault_secret "delete_home_cluster_info_vault_item" do
  admins []
  id 'home-cluster-info'
  data_bag home_data_bag_name
  action :delete
end

chef_vault_secret "delete_remote_cluster_info_vault_item" do
  admins []
  id 'remote-cluster-info'
  data_bag home_data_bag_name
  action [:delete, :delete]
end
```

Its seems the reason is because this lwrp calls `:delete` actions using cheffish resource `chef_data_bag_item`. For some reason cheffish does not delete the item if only `:delete` is called, not sure the reason for that logic.

https://github.com/chef-cookbooks/chef-vault/blob/master/libraries/chef_vault_secret.rb#L100
https://github.com/chef/cheffish/blob/master/lib/chef/resource/chef_data_bag_item.rb#L86
https://github.com/chef/cheffish/blob/master/lib/cheffish/base_resource.rb#L23

My workaround:
```
%w(home-cluster-info remote-cluster-info).each do |item|
  chef_data_bag_item item do
    data_bag home_data_bag_name
    action [:delete, :delete]
  end

  chef_data_bag_item [item, 'keys'].join('_') do
    data_bag home_data_bag_name
    action [:delete, :delete]
  end
end
```

**Comment by ndobson** [comment]
This is because the `:delete` action of `chef_vault_secret` doesn't pass in the `data_bag` property to `chef_data_bag_item`
This workaround would also work:
```
chef_vault_secret "delete_home_cluster_info_vault_item" do
  admins []
  id "#{home_data_bag_name}/home-cluster-info"
  data_bag home_data_bag_name
  action :delete
end
```
Should be an easy fix, I'll submit a pr.
