### ISSUE TITLE
No resource or method named `chef_vault_item' for `Chef::Recipe

### ISSUE THREAD

**Issue by thinkrapido** [chef-cookbooks/chef-vault#52]
### Cookbook version

latest
### Chef-client version

12.8.1
### Platform Details

ubuntu 14.04
### Scenario:

Use chef_vault_item method

`No resource or method named`chef_vault_item' for `Chef::Recipe`

What prerequisites do I need to use this method during bootstrapping a node
### Steps to Reproduce:

knife bootstrap ...
### Expected Result:

Method can be used
##

**Comment by cheeseplus** [comment]
Given there has been a major version change and this problem doesn't seem present, closing. If the issue is preventing itself in current version please open a new issue.
