### ISSUE TITLE
Add options resource attribute for chef_gem

### ISSUE THREAD

**Issue by domofactor** [chef-cookbooks/chef-vault#56]
### Cookbook version
2.0.0

### Scenario:
I'm trying to use this cookbook from behind a firewall. So, I need to ability to pass gem install options to the chef_gem resource. in my case, -p for http_proxy.

PR #57

**Comment by domofactor** [comment]
Create a PR to fix this: https://github.com/chef-cookbooks/chef-vault/pull/57

**Comment by thommay** [comment]
This was merged, thanks.
