### ISSUE TITLE
No longer being installed 

### ISSUE THREAD

**Issue by awworrell** [chef-cookbooks/chef-vault#62]
### Cookbook version
0.16.1
### Chef-client version
12.11.18

### Platform Details
Ubuntu 14.04

### Scenario:
I am trying to install percona via test kitchen and it has been broken since chef vault was upgraded.

### Steps to Reproduce:
When I tr to compile chef-vault 3.0.3 I get this error 
--- Begin output of bundle install ----
       STDOUT: Don't run Bundler as root. Bundler can ask for sudo if it is needed, and
       installing your bundle as root will break this application for all non-root
       users on this machine.
       Fetching gem metadata from https://rubygems.org/..........
       Fetching version metadata from https://rubygems.org/..
       Resolving dependencies...
       Installing chef-vault 3.0.3

       Gem::InstallError: chef-vault requires Ruby version >= 2.2.0.
       Using bundler 1.11.2
       An error occurred while installing chef-vault (3.0.3), and Bundler cannot
       continue.
       Make sure that `gem install chef-vault -v '3.0.3'` succeeds before bundling.
       STDERR:

### Expected Result:
It installs correctly

### Actual Result:
--- Begin output of bundle install ----
       STDOUT: Don't run Bundler as root. Bundler can ask for sudo if it is needed, and
       installing your bundle as root will break this application for all non-root
       users on this machine.
       Fetching gem metadata from https://rubygems.org/..........
       Fetching version metadata from https://rubygems.org/..
       Resolving dependencies...
       Installing chef-vault 3.0.3

       Gem::InstallError: chef-vault requires Ruby version >= 2.2.0.
       Using bundler 1.11.2
       An error occurred while installing chef-vault (3.0.3), and Bundler cannot
       continue.
       Make sure that `gem install chef-vault -v '3.0.3'` succeeds before bundling.
       STDERR:

**Comment by thommay** [comment]
Thanks for filing this issue. 
I'd recommend ensuring that your chef version is up to date and then trying again. Otherwise, staying on the 2 series of chef-vault will be more appropriate.

**Comment by awworrell** [comment]
I am not able at the moment to upgrade chef and its taken down or our production environments so that we can't use chef anymore. Is it possible to get a fix in so that it would work?

**Comment by thommay** [comment]
If you're using the chef-vault cookbook, set `node['chef-vault']['version']` to `'2.9.1'`, we won't be downgrading the required ruby version of the gem.

**Comment by aHaydenLSS** [comment]
I'm getting this same result while using chef 12.10.24 and trying to install chef-vault 3.3.0. I can't change the versions of these, because they are currently used by an existing product (which I'm trying to run locally). However, my coworkers have gotten these to work fine using the same commands I have. If somebody could help me work around this it would be greatly appreciated as I've been trying to get this to work for a day now...
