### ISSUE TITLE
4.0.3 Release incoming?

### ISSUE THREAD

**Issue by gravesb** [chef-cookbooks/chef-vault#86]
I would like to upgrade my cookbook to use the 4.x line in order to maintain compatibility with Chef 16, but if I do so then I believe I would lose compatibility with Chef 15 and below.  The problem has already been fixed in the master branch [here](https://github.com/chef-cookbooks/chef-vault/commit/3a097e7152f75a0b6303b0e7d7530cba7511f653). Can we get that latest code released?

**Comment by gravesb** [comment]
Bump, @tas50?

**Comment by tas50** [comment]
It's up on supermarket now. I totally spaced on this.

**Comment by gravesb** [comment]
Awesome.  Thanks.
